import Head from 'next/head'

import Sidebar from 'components/Sidebar'
import SignIn from "components/SignIn"
import { Box,Text } from '@chakra-ui/react'
export default function Home() {
  return (
    <>
      <Head>
        <title>Eve Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Box >
<Sidebar />

<SignIn/>


     </Box>
    </>
  )
}
