import Head from 'next/head'
import StatsHome from 'components/StatsHome'

import Sidebar from 'components/Sidebar'
import SignIn from "components/SignIn"
import { Box,Text } from '@chakra-ui/react'
import { AuthContext } from 'context/authContext';
import { useContext } from 'react';
export default function Home() {
  const {name}= useContext(AuthContext)
  return (
    <>
      <Head>
        <title>Eve Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Box display={"flex"}>
<Sidebar />


{name?.length ? <StatsHome/> : <SignIn/> }

     </Box>
    </>
  )
}
